### ISSUE TITLE
Installation Unsuccessful 

### ISSUE THREAD

**Issue by UGuntupalli** [grid-parity-exchange/Egret#134]
I am trying to follow through the instructions and install the package but I have been unsuccessful. I would appreciate some guidance and help, please point out if I am doing something obviously wrong. I am using Anaconda Prompt all through to attempt the package installation.  I am using Windows 10 and Conda version  4.8.3.

1. Git Clone the repository - successful, no problem 
2. Open Anaconda Prompt and create an environment
      ```python 
         conda create --name erget_test
      ```
3. Install Pyomo 
    ```python 
       conda install -c conda-forge pyomo
    ```
4. Install open-source solvers 
    ```python
       conda install -c conda-forge ipopt glpk
    ```
5. Install pytest
    ```python 
       pip install pytest
    ```
6. Install coincbc
    ```python
       conda install -c conda-forge coincbc
    ``` 
     This fails throwing a PackagesNotFoundError 
   
<img width="510" alt="cmd_NEn4l4jUFw" src="https://user-images.githubusercontent.com/47903157/87488208-a0e0ca80-c5f4-11ea-98b3-7024f2897ffd.png">

Additionally, the last instruction around running setup.py is not really clear, I have tried several different ways to invoke and run setup.py, but I am not sure I understand what works: 

<img width="949" alt="XycLFO9054" src="https://user-images.githubusercontent.com/47903157/87488468-50b63800-c5f5-11ea-8115-453b1c03d8d3.png">

**Comment by UGuntupalli** [comment]
@rconcep : 
 I realized you have started contributing on this project now. I am having a really hard time, just getting the package installed and pass the tests, can you offer some help  ?

**Comment by bknueven** [comment]
Regarding (6), cbc is not available via conda-forge for windows. Installation instructions for windows can be found here: [https://projects.coin-or.org/Cbc](https://projects.coin-or.org/Cbc). That said, you don't strictly need an open-source solver if you have access to a commercial solver (i.e., CPLEX or Gurobi, for now).

Regarding the setup.py run, it would be unusually for your python.exe executable to be located in your Egret directory. You should be able to just run `python.exe` as a stand-alone executable if your python is correctly installed.
