### ISSUE TITLE
The second test fails: --runmip error

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [grid-parity-exchange/Egret#135]
I have installed it successfully: Windows 10, newest anaconda, ILOG CPLEX 12.10, etc.
1-This is the output of pytest test_unit_commitment.py

================================================= test session starts ====================
platform win32 -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: C:\Users\some-user\Egret-master
plugins: hypothesis-5.5.4, arraydiff-0.3, astropy-header-0.1.2, doctestplus-0.5.0, openfiles-0.4.0, remotedata-0.3.2
collected 21 items

test_unit_commitment.py .....................                                                                    [100%]

=========================================== 21 passed in 2804.02s (0:46:44) ==================
**it took more than 46 min, isn't it a bit slow on my system?**

 2-This is the output of pytest --runmip test_unit_commitment.py

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: **error: unrecognized arguments: --runmip**
  inifile: None
**Any idea about fixing the error?**

**Comment by bknueven** [comment]
Somebody (me) changed the behavior of that test without updating the associated documentation. It now looks for a commercial MIP solver and runs the MIP tests automatically if it finds one.

I agree that 46-minutes is a bit slow, but not out of the question. At some point the unit commitment tests should really be re-worked (#113).

**Comment by MajidSKhoshghalb** [comment]
Thanks !
