### ISSUE TITLE
Tests fail for Gurobi solver

### ISSUE THREAD

**Issue by goghino** [grid-parity-exchange/Egret#146]
I have run the tests following the installation instructions (execute `pytest test_unit_commitment.py` from `models/tests sub-directory`). I have the latest Gurobi (AMPL-Gurobi 9.0.1) installed at macOS. 

The result of the test is following: **21 failed, 1 warning in 814.40s (0:13:34)**
The full log is here [Gurobi log](https://gist.github.com/goghino/34ba4022790ad0c7a96790973d60ec0e)

I've tried to run the tests with different solvers, e.g.
SCIP: **18 failed, 3 passed, 1 warning in 241.02s (0:04:01)**
log: [SCIP log](https://gist.github.com/goghino/d40bee46e072168f5b8c16dde306496d)

CBC: **1 failed, 20 passed, 1 warning in 2765.15s (0:46:05)**
log: [CBC log](https://gist.github.com/goghino/06d97bc286f11f7c163485597c6a13c7)

Can anybody give me some pointers how to fix the tests? Thanks!

**Comment by bknueven** [comment]
Based on the output logs provided, I have the following suggestions:
1. For Gurobi, it looks like there's an issue with the way the solver is configured for Pyomo. Can you solve any Pyomo model using Gurobi?
1. For SCIP (which is admittedly not tested, or explicitly supported), the issue looks similar: all the MIP solves return +infinity, which seems like an issue with either the solver or how it is interfacing to Pyomo. I would try solving a small MIP with Pyomo+SCIP.
1. The CBC failure doesn't particularly concern me: CBC sometimes returns wrong/different results, and the returned value in close to the reference.  There's also a general issue with the unit commitment tests being somewhat numerically unstable; see #125.

**Comment by goghino** [comment]
Thanks @bknueven,

indeed, there was something strange with my Gurobi installation. Yesterday I tried solving some small example after installing Gurobi and it seemed working fine. Today, I couldn't even reproduce the failure of the tests getting
`pyutilib.common._exceptions.ApplicationError: No executable found for solver 'gurobi'`.

After setting 
```
export PATH=$PATH:/Library/gurobi901/mac64/bin
export GUROBI_HOME=/Library/gurobi901/mac64

```
and updating the licence with `grbgetkey` the results are OK.

```
(UnitCommitment) Juraj@Manin (master):~/Documents/Optimization/pyomo/Egret/egret/models/tests$ pytest test_unit_commitment.py
======================================== test session starts ========================================
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/Juraj/Documents/Optimization/pyomo/Egret
collected 21 items

test_unit_commitment.py .....................                                                 [100%]

========================================= warnings summary ==========================================
/Users/Juraj/anaconda3/envs/UnitCommitment/lib/python3.8/site-packages/pyutilib/misc/import_file.py:11
  /Users/Juraj/anaconda3/envs/UnitCommitment/lib/python3.8/site-packages/pyutilib/misc/import_file.py:11: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================ 21 passed, 1 warning in 1413.26s (0:23:33) =============================
```
