### ISSUE TITLE
_include_feasibility_slack improvments

### ISSUE THREAD

**Issue by DLWoodruff** [grid-parity-exchange/Egret#162]
_include_feasibility_slack currently has a named argument called "penalty" that defaults to 1000. I suggest the following improvements:

1. replace this argument with two named arguments with defaults shown : 
per_unit_slack_penalty=None and slack_factor=10
The code should assert that one is None and the other is not None.
The argument slack_factor would work exactly like the current argument called penalty.
The argument  per_unit_slack_penalty would be assigned directly to p_penalty and q_penalty

2. These arguments should be exposed all the way up to the create_* function (e.g.,
all the way up to create_riv_acopf_model, etc.)

Aside: It might be good to have a standardized way to pass arguments from the highest levels of Egret to the lowest, but that is a different issue.

**Comment by bknueven** [comment]
I agree entirely -- I just want to comment that the per_unit_slack_penalty already has a corollary in the unit commitment model `ModelData.data['system']['load_mismatch_cost']` and `ModelData.data['system']['q_load_mismatch_cost']`, set [here](https://github.com/grid-parity-exchange/Egret/blob/8a396c9191a5c8905ca93c3f9cf9b9f223a10d73/egret/model_library/unit_commitment/params.py#L1232).

This attributes are also already scaled appropriately by `egret.model_library.transmission.tx_utils.scale_ModelData_to_pu`, so they could just be read and used directly for @DLWoodruff 's `per_unit_slack_penalty`, albeit with potentially different values for p_load and q_load.

**Comment by jeanpaulwatson** [comment]
I believe I've addressed this (for AC models) in #163. I decided that penalties are something that one should understand, or at least be aware of. So no more automatic calculation of them in EGRET. They have to be specified, period. Further, they have to be passed in through the model-data dictionary, analogous to what occurs in the UC model builders.

**Comment by jeanpaulwatson** [comment]
Closed for AC models (which @DLWoodruff was addressing when he opened this issue) by #163. A subsequent PR will address for DC models.
