### ISSUE TITLE
Some features not precisely preserved after dumping/loading from json

### ISSUE THREAD

**Issue by bknueven** [grid-parity-exchange/Egret#3]
The most vexing of which is the description of the polynomial cost curve, for which we assume the 'values' dictionary has integer keys in several places. Here is the original.
```
{'data_type': 'cost_curve',
 'cost_curve_type': 'polynomial',
 'values': {0: 37, 1: 25.26, 2: 0.00712}}
```
Same after dumping/loading from json.
```
{'data_type': 'cost_curve',
 'cost_curve_type': 'polynomial',
 'values': {'0': 37, '1': 25.26, '2': 0.00712}}
```

Obviously this isn't a big deal technically, but how should we address it? Two obvious things are to make the model builders aware some things may be strings (and convert appropriately) or write a json parser that makes these substitutions where appropriate.

**Comment by anyacastillo** [comment]
Would it be an odd solution to require that all dict keys are strings? Then
we wouldn’t have to worry about any special processing when dumping/loading
to/from json.

**Comment by bknueven** [comment]
No, but we would need to modify some of the constraint declarations. `For` example, this comes up in the cost builder expression in egret/model_library/transmission/gen.py:
```
assert p_costs[gen_name]['cost_curve_type'] == 'polynomial'
m.pg_operating_cost[gen_name] = \
                sum(v*m.pg[gen_name]**i for i, v in p_costs[gen_name]['values'].items())
```
Right now if we read in something from json as-is we'll end up raising a variable to a str power. Just re-factoring to use int(i) in place of i would definitely work.
