### ISSUE TITLE
Need to protect stack graph generation viz tests, in case matplotlib and seaborn are not installed.

### ISSUE THREAD

**Issue by jwatsonnm** [grid-parity-exchange/Egret#36]
For @rconcep : Can you add skip-if logic for the stackgraph generation tests, in case matplotlib or seaborn are not installed? I am going to add both of those packages as a dependency for auto install in setup.py, but I think it still would be a good idea in case viz packages are not properly installed / functioning on some platforms.

**Comment by rconcep** [comment]
> 
> 
> For @rconcep : Can you add skip-if logic for the stackgraph generation tests, in case matplotlib or seaborn are not installed? I am going to add both of those packages as a dependency for auto install in setup.py, but I think it still would be a good idea in case viz packages are not properly installed / functioning on some platforms.

Sure. I think there's an example of that skipping in this repo (checking if Gurobi is available).
