### ISSUE TITLE
Pytest should not be a requirement in setup.py

### ISSUE THREAD

**Issue by michaelbynum** [grid-parity-exchange/Egret#40]

**Comment by jwatsonnm** [comment]
We should have a discussion on the topic of dependency install in general, as we obviously don't have a unified philosophy here. What is your concern about pytest? If we're already doing numpy, matplotlib, and seaborn, I figured pytest would have minimal impact.

**Comment by jwatsonnm** [comment]
Also: If we take out pytest, then I'm not sure how users can verify their install.

**Comment by michaelbynum** [comment]
Good point.
